name: Build and publish demo on GitHub pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Setup PHP 8.3"
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Configure authentication for composer
      run: git config --global github.accesstoken $GITHUB_TOKEN

    - name: Build demo
      run: bash .ci/build-demo.sh
      env:
        SATIS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload static files from public as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: public/

  # Deploy pages
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
